services:
  react-app:
    build:
      context: ./react-app
      dockerfile : Dockerfile
    image: 'react-image:latest'
    container_name: 'react-container'
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./react-app:/react-app
      - .env:/.env
    depends_on:
      - springboot-app
    ports:
      - ${REACT_HOST_PORT}:${REACT_SERVER_PORT}
    env_file:
      - .env
    networks:
      - inha
      
  springboot-app:
    build:
      context: ./springboot-app
      dockerfile : Dockerfile
    image: 'springboot-image:latest'
    container_name: 'springboot-container'
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./springboot-app:/springboot-app
      - .env:/.env
    ports:
      - ${SPRINGBOOT_HOST_PORT}:${SPRINGBOOT_SERVER_PORT}
    env_file:
      - .env
    networks:
      - inha

networks:
  inha:
    name: inha